class LegalSection {
  const LegalSection({required this.title, required this.body});

  final String title;
  final String body;
}

class ProfileLegalContent {
  static const faqs = [
    LegalSection(
      title: 'What is Zara?',
      body:
          'Zara is your AI companion for chat, voice notes, and meaningful conversation. '
          'She remembers context within your session and responds in a warm, natural tone.',
    ),
    LegalSection(
      title: 'Are my messages private?',
      body:
          'Your conversations are stored securely on our servers so Zara can reply and '
          'continue the chat across sessions. We do not sell your personal messages.',
    ),
    LegalSection(
      title: 'How do voice notes work?',
      body:
          'Tap and hold the mic to record, or tap once to lock recording. Slide left while '
          'holding to cancel. Voice notes are transcribed and sent like regular messages.',
    ),
    LegalSection(
      title: 'Can I change the theme?',
      body:
          'Yes. Open the menu from the chat header, then choose Light theme or Dark theme.',
    ),
    LegalSection(
      title: 'How do I get help?',
      body:
          'Go to Profile → Support to email our team at hello@crowstone.ai. '
          'We typically respond within one business day.',
    ),
  ];

  static const privacyPolicy = '''
Last updated: June 2026

Crowstone ("we", "us") operates the Zara companion app. This policy explains how we handle information when you use the app.

Information we collect
• Account identifiers created when you use the app (such as a guest username).
• Messages, voice notes, and interaction events needed to provide chat features.
• Basic device and app diagnostics to keep the service reliable.
• On Android, device or advertising identifiers (such as the advertising ID) collected by our attribution partner AppsFlyer to measure installs, campaign performance, and deep-link routing.

How we use information
• To deliver AI chat and voice features.
• To improve product quality, safety, and support.
• To respond to support requests you send us.
• To measure marketing effectiveness and attribute app installs (via AppsFlyer).

Data retention
We retain conversation data while your account is active so Zara can maintain context. If you delete your account from the app, we remove associated local credentials and request deletion of server-side account data where supported.

Sharing
We do not sell personal data. We may use trusted infrastructure providers (hosting, analytics) strictly to operate the service. On Android, AppsFlyer may receive device or advertising identifiers for attribution and analytics as described above.

Your choices
You can log out, delete your account from Profile → Account, or contact us to request data access or deletion. On Android, you can limit ad personalization or reset your advertising ID in your device settings.

Contact
hello@crowstone.ai
''';

  static const termsAndConditions = '''
Last updated: May 2026

By using Zara, you agree to these Terms.

The service
Zara is an AI companion for entertainment and conversation. Responses are generated by AI and may be inaccurate, incomplete, or inappropriate in edge cases. Do not rely on Zara for medical, legal, financial, or emergency advice.

Acceptable use
You agree not to misuse the app, attempt to break security, harass others, or upload unlawful content.

Accounts
You are responsible for activity on your account. You may log out or delete your account at any time from Profile → Account.

Disclaimer
The app is provided "as is" without warranties. To the maximum extent permitted by law, Crowstone is not liable for indirect or consequential damages arising from use of the app.

Changes
We may update these Terms. Continued use after changes means you accept the updated Terms.

Contact
hello@crowstone.ai
''';
}
