class LegalSection {
  const LegalSection({required this.title, required this.body});

  final String title;
  final String body;
}

class ProfileLegalContent {
  static const lastUpdated = 'June 6, 2026';

  static const faqs = [
    LegalSection(
      title: 'What is Zara?',
      body:
          'Zara is your AI companion for chat, voice notes, and meaningful conversation. '
          'She is an artificial character, not a real person. Responses are generated by AI.',
    ),
    LegalSection(
      title: 'What is private mode?',
      body:
          'Private mode is an optional paid feature for users 18 and older. It unlocks romantic-style '
          'AI chat and curated images from Zara for 30 days. Normal friend-mode chat stays available '
          'outside private mode.',
    ),
    LegalSection(
      title: 'Are Zara\'s photos real?',
      body:
          'Photos sent in private mode are curated app content for the Zara character. They are not '
          'live camera photos from a real person.',
    ),
    LegalSection(
      title: 'What happens when I exit private mode?',
      body:
          'Messages you sent and received while private mode was on are removed from your chat history. '
          'Your normal (non-private) conversation with Zara remains.',
    ),
    LegalSection(
      title: 'Are my messages private?',
      body:
          'Conversations are stored on our servers so Zara can reply and continue across sessions. '
          'Private mode is not end-to-end encrypted. We do not sell your personal messages.',
    ),
    LegalSection(
      title: 'How do payments work?',
      body:
          'Private mode uses a Cashfree auto-pay mandate. You pay \u20B91 today for a 1-day trial, '
          'then \u20B9199/month is auto-debited until you cancel. We do not store your full card details.',
    ),
    LegalSection(
      title: 'How do voice notes work?',
      body:
          'Tap and hold the mic to record, or tap once to lock recording. Slide left while '
          'holding to cancel. Voice notes are transcribed and sent like regular messages.',
    ),
    LegalSection(
      title: 'Can I change the theme?',
      body:
          'Yes. Open the menu from the chat header, then choose Light theme or Dark theme.',
    ),
    LegalSection(
      title: 'How do I get help?',
      body:
          'Go to Profile → Support to email our team at hello@crowstone.ai. '
          'We typically respond within one business day.',
    ),
  ];

  static const privacyPolicy = '''
Last updated: $lastUpdated

Crowstone ("we", "us") operates the Zara companion app. This policy explains how we handle information when you use the app.

Information we collect
• Account identifiers (such as a guest or chosen username) and credentials if you create an account.
• Age (number), when you provide it to access private mode — used to confirm you are 18 or older.
• Messages, voice notes, and optional images shown in chat.
• Private-mode status, purchase-related records (such as order id and pass expiry), and product analytics events (for example private mode banner taps or pay button clicks).
• Usage and interaction analytics — such as screens and pages viewed, taps, app performance, a device or browser analytics identifier, and an approximate location (country or region) derived from your IP address — collected through our analytics provider PostHog. When you sign in, these analytics may be linked to your account.
• Basic device and app diagnostics to keep the service reliable.
• On Android, device or advertising identifiers (such as the advertising ID) collected by our attribution partner AppsFlyer to measure installs, campaign performance, and deep-link routing.

How we use information
• To deliver AI chat, voice notes, and private-mode features (including romantic-style replies and curated images).
• To process payments and manage your private-mode access period.
• To improve product quality, safety, and support.
• To respond to support requests you send us.
• To measure marketing effectiveness and attribute app installs (via AppsFlyer).

Private mode and messages
• Private mode is intended only for users 18 and older.
• While private mode is on, messages are tagged as private. When you exit private mode, those private messages are deleted from your history. Normal chat messages are kept.
• Private mode is processed on our servers; it is not end-to-end encrypted.

Photos and storage
• In private mode, Zara may send images from our curated catalog. These are not photos taken by a real person in real time.
• Voice notes and images may be stored in secure cloud object storage. The app may load them using time-limited access links.

AI and service providers
• We use third-party providers (such as AI, speech, hosting, payment, and analytics services) to operate Zara. Your content may be processed by these providers only to deliver and improve the service.
• Our product-analytics provider, PostHog, processes the usage and interaction analytics described above on our behalf using EU-based infrastructure.

Cookies and similar technologies
• On the web, we and our providers use cookies and similar browser storage to keep you signed in, remember preferences, measure how the product is used (PostHog analytics), and measure marketing performance (Google).
• You can clear or block cookies in your browser settings, though some features may not work correctly without them.
• The mobile app does not use browser cookies; it stores a local analytics identifier and queued analytics events on your device.

Payments
• Private mode purchases are handled by Cashfree. We receive payment status and order information from the processor. We do not store your full payment card details.

Data retention
• We retain conversation data while your account is active so Zara can maintain context, subject to private-mode deletion when you exit private mode.
• If you delete your account from the app, we remove associated local credentials and request deletion of server-side account data where supported.
• We may retain limited records where required for law, safety, fraud prevention, or payment disputes.

Sharing
• We do not sell personal data.
• We use trusted infrastructure providers (hosting, storage, analytics, payments, AI) strictly to operate the service.
• On Android, AppsFlyer may receive device or advertising identifiers for attribution and analytics as described above.

Children
• The app and private mode are not intended for anyone under 18.

Your choices
• You can log out, delete your account from Profile → Account, or contact us to request data access or deletion.
• On Android, you can limit ad personalization or reset your advertising ID in your device settings.
• On the web, you can clear or block cookies in your browser to limit analytics and marketing measurement.
• Exiting private mode removes private-mode messages from your chat history.

Contact
hello@crowstone.ai
''';

  static const termsAndConditions = '''
Last updated: $lastUpdated

By using Zara, you agree to these Terms.

The service
• Zara is an AI companion for entertainment and conversation. She is not a real person.
• Responses and images are generated or curated by AI and technology partners. They may be inaccurate, incomplete, or inappropriate in edge cases.
• Do not rely on Zara for medical, legal, financial, or emergency advice.

Eligibility and private mode
• You must be 18 years or older to purchase or use private mode.
• You agree to provide accurate age information. We may suspend or end access if you are under 18 or misuse the feature.
• Private mode includes romantic-style AI chat and curated images for a 30-day access period unless stated otherwise at purchase.
• Private mode is for entertainment. It does not create a real-world relationship with any person.

Private mode and data
• Messages sent while private mode is active may be deleted when you exit private mode. Other messages may remain.
• Private mode is not end-to-end encrypted. Do not share information you cannot risk being processed on our systems.

Payments and refunds
• Private mode fees are processed by Cashfree. Prices and duration are shown before you pay.
• Purchases are generally non-refundable except where required by applicable law or where a payment failed but access was not granted. Contact hello@crowstone.ai for billing issues.

Acceptable use
• You agree not to misuse the app, break security, harass others, upload unlawful content, or use the service to harm minors.
• You will not use Zara to solicit illegal content or activity.

Accounts
• You are responsible for activity on your account. You may log out or delete your account at any time from Profile → Account.

Disclaimer
• The app is provided "as is" without warranties. Romantic and private-mode features are entertainment only.
• To the maximum extent permitted by law, Crowstone is not liable for indirect or consequential damages arising from use of the app.

Changes
• We may update these Terms or change features, pricing, or access periods. Continued use after changes means you accept the updated Terms where permitted by law.

Contact
hello@crowstone.ai
''';
}
