name: mia_companion
description: Zara AI companion — chat, voice notes, and realtime calls.
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  record: ^6.2.0
  permission_handler: ^11.3.1
  just_audio: ^0.9.42
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  flutter_pcm_sound: ^3.1.1
  audio_session: ^0.1.25
  url_launcher: ^6.3.1
  http_parser: ^4.1.2
  web: ^1.1.1
  flutter_cashfree_pg_sdk: ^2.4.0+52
  font_awesome_flutter: ^11.0.0
  video_player: ^2.11.1
  appsflyer_sdk: ^6.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.png
  adaptive_icon_background: "#12081F"
  adaptive_icon_foreground: assets/images/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/mia_profile.png
    - assets/images/auth_background.png
    - assets/images/zara_gallery/
    - assets/onboarding_video.mp4
